"""initial schema with all media types and duplicate log

Revision ID: 66dc623599d9
Revises: 
Create Date: 2026-05-01 14:07:51.573305
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dc623599d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('video_threshold', sa.Integer(), nullable=False),
    sa.Column('duplicates_deleted', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('duplicate_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('original_message_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_message_id', sa.Integer(), nullable=False),
    sa.Column('detection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('action_taken', sa.String(length=10), nullable=False),
    sa.Column('hamming_distance', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_duplicate_log_chat', 'duplicate_log', ['chat_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_duplicate_log_chat_id'), 'duplicate_log', ['chat_id'], unique=False)
    op.create_table('media_hashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('secondary_hash', sa.String(length=64), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.String(length=200), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_hashes_chat_file', 'media_hashes', ['chat_id', 'file_hash'], unique=False)
    op.create_index(op.f('ix_media_hashes_chat_id'), 'media_hashes', ['chat_id'], unique=False)
    op.create_index('ix_media_hashes_chat_secondary', 'media_hashes', ['chat_id', 'secondary_hash'], unique=False)
    op.create_index(op.f('ix_media_hashes_file_hash'), 'media_hashes', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_hashes_file_hash'), table_name='media_hashes')
    op.drop_index('ix_media_hashes_chat_secondary', table_name='media_hashes')
    op.drop_index(op.f('ix_media_hashes_chat_id'), table_name='media_hashes')
    op.drop_index('ix_media_hashes_chat_file', table_name='media_hashes')
    op.drop_table('media_hashes')
    op.drop_index(op.f('ix_duplicate_log_chat_id'), table_name='duplicate_log')
    op.drop_index('ix_duplicate_log_chat', table_name='duplicate_log')
    op.drop_table('duplicate_log')
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
